# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: NVIDIACorporation.NVIDIAapp
PackageVersion: 1.0.14.0
PackageLocale: en-US
Publisher: NVIDIA Corporation
PackageName: NVIDIA app
License: Proprietary
Copyright: Copyright © 2011-2024 NVIDIA Corporation
ShortDescription: The NVIDIA application integrates the functionalities of the NVIDIA Control Panel, GeForce Experience, and RTX Experience applications.
ManifestType: defaultLocale
ManifestVersion: 1.6.0
